version: '3.8'

services:
  gamemanager:
    build: .
    container_name: gamemanager
    ports:
      - "5000:5000"
    volumes:
      # Mount application data directories
      - ./roms:/opt/gamemanager/roms
      - ./var:/opt/gamemanager/var
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app.py
      # IGDB API Credentials (set these in your environment or .env file)
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # Security options
    security_opt:
      - no-new-privileges:true
    # User mapping (optional)
    user: "1000:1000"
    # Network mode
    network_mode: "bridge"

# Optional: Add a reverse proxy service
# Uncomment if you want to use nginx as reverse proxy
# services:
#   nginx:
#     image: nginx:alpine
#     container_name: cursorscraper-nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./ssl:/etc/nginx/ssl:ro
#     depends_on:
#       - cursorscraper
#     restart: unless-stopped
